---
- name: Ensure firewalld service is not enabled
  systemd:
    name: firewalld
    state: stopped
    enabled: False
    masked: True
  register: task_result
  failed_when:
    - task_result is failed
    - ('could not' not in task_result.msg | lower)

- name: Wait 10 seconds after disabling firewalld
  pause:
    seconds: 10
  when: task_result is changed

- name: Install iptables packages
  package:
    name:
      - iptables
      - iptables-services
    state: present
  register: result
  until: result is succeeded
  when: ansible_os_family == 'RedHat'
  
- name: Install iptables packages
  package:
    name:
      - iptables
      - iptables-persistent
    state: present
  register: result
  until: result is succeeded
  when: ansible_os_family == 'Debian' and ansible_distribution != 'Ubuntu' 

- name: Install IFW Ubuntu packages
  package:
    name:
      - ufw
    state: present
  register: result
  until: result is succeeded
  when: ansible_os_family == 'Ubuntu'


- name: Start and enable iptables service
  systemd:
    name:  iptables
    state: started
    enabled: True
    masked: False
    daemon_reload: yes
  register: result
  when: ansible_os_family == 'Debian' and ansible_distribution != 'Ubuntu' 

- name: Start and enable UFW service
  systemd:
    name:  ufw
    state: started
    enabled: True
    masked: False
    daemon_reload: yes
  register: result
  when: ansible_distribution == 'Ubuntu' 

- name: need to pause here, otherwise the iptables service starting can sometimes cause ssh to fail
  pause:
    seconds: 10
  when: result is changed
