---
- name: Ensure firewalld service is not enabled
  systemd:
    name: firewalld
    state: stopped
    enabled: no
    masked: yes
  register: task_result
  failed_when:
    - task_result is failed
    - ('could not' not in task_result.msg | lower)

- name: Wait 10 seconds after disabling firewalld
  pause:
    seconds: 10
  when: task_result is changed

- name: Install iptables packages
  package:
    name:
      - iptables
      - iptables-services
    state: present
  register: result
  until: result is succeeded

- name: Start and enable iptables service
  systemd:
    name: iptables
    state: started
    enabled: yes
    masked: no
    daemon_reload: yes
  register: result

- name: need to pause here, otherwise the iptables service starting can sometimes cause ssh to fail
  pause:
    seconds: 10
  when: result is changed
